version: '3.3'
services:
  nexus:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    container_name: nexus
    volumes:
     - ./data:/nexus-data