version: '3.8'
services:
  gitbucket:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    container_name: gitbucket
    volumes:
     - ./data:/gitbucket/gitbucket