version: '3.3'
services:
  jenkins:
    #build: .
    image: jenkins
    ports:
      - 8080:8080
      #- 50000:50000  
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_SERVER_IP=localhost
    volumes:
     - ./data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock