version: '3.8'
services:
  portainer:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: portainer
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
networks:
  default:
    name: sdlc